Public Module HelperClassDefs
    Public Const EVENT_SCHEDULER_CLASSDEF As String = "' <auto-generated>
'     This code was generated by `ModuleEventRaiser.Generator`.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Option Explicit On
Option Strict On
Imports System
Imports System.Collections.Generic
Imports System.Linq

''' <summary>
''' Provides a unified event scheduling mechanism for modules, allowing events to be deferred until a later time.
''' </summary>
''' <remarks>
''' <para>
''' This class is especially useful in game development frameworks such as MonoGame, FNA, and Unity,
''' where raising events during the update phase can lead to performance issues or race conditions.
''' By scheduling events for later execution, typically during the draw phase, you can keep frame rates
''' stable and make event handling more predictable.
''' </para>
''' <para>
''' <b>Priority System:</b> Events can be scheduled with different priority values. Higher-priority
''' events are raised first. When multiple events share the same priority, they are raised in
''' first-in, first-out (FIFO) order.
''' </para>
''' <para>
''' <b>Thread Safety:</b> All methods in this class are thread-safe and may be called from any thread.
''' </para>
''' <para>
''' <b>Usage Example:</b>
''' <code lang=""vb"">
''' ' Schedule an event with the default priority by wrapping a RaiseEvent call
''' EventScheduler.ScheduleEventAction(
'''     Sub()
'''         Debug.WriteLine($""[ModuleEventScheduler] MyEvent raised with args: {{arg1}}, {{arg2}}"")
'''         RaiseEvent_MyEvent(arg1, arg2)
'''     End Sub)
'''
''' ' Schedule a high-priority event in the same way
''' EventScheduler.ScheduleEventAction(
'''     Sub()
'''         Debug.WriteLine($""[ModuleEventScheduler] CriticalEvent raised with data: {{data}}"")
'''         RaiseEvent_CriticalEvent(data)
'''     End Sub, priorityValue:=10)
'''
''' ' Later, typically during the Draw phase in the game framework:
''' EventScheduler.RaiseScheduledEvents()
''' </code>
''' </para>
''' </remarks>
Public NotInheritable Class ModuleEventScheduler
    Private Structure EventItem
        Public ReadOnly [Event] As Action
        Public ReadOnly Priority As Integer
        Public ReadOnly Order As Integer

        Public Sub New([event] As Action, priority As Integer, order As Integer)
            Me.Event = [event]
            Me.Priority = priority
            Me.Order = order
        End Sub
    End Structure

    Private ReadOnly _pendingEvents As New List(Of EventItem)
    Private ReadOnly _lock As New Object

    ''' <summary>
    ''' Schedules an event action for later execution with an optional priority value.
    ''' </summary>
    ''' <param name=""eventAction"">The event action to schedule. This is typically a lambda that raises an event.</param>
    ''' <param name=""priorityValue"">The priority value for the event (default value: 0).
    ''' Higher-priority events are raised first. When multiple events share the same priority,
    ''' they are raised in FIFO order.</param>
    ''' <exception cref=""ArgumentNullException"">Thrown when <paramref name=""eventAction""/> is null.</exception>
    ''' <remarks>
    ''' This method is thread-safe and may be called from any thread. The scheduled event will be
    ''' raised when <see cref=""RaiseScheduledEvents""/> is invoked.
    ''' </remarks>
    Public Sub ScheduleEventAction(eventAction As Action, Optional priorityValue As Integer = 0)
        ArgumentNullException.ThrowIfNull(eventAction)
        SyncLock _lock
            _pendingEvents.Add(New EventItem(eventAction, priorityValue, _pendingEvents.Count))
        End SyncLock
    End Sub

    ''' <summary>
    ''' Raises all scheduled event actions in priority order.
    ''' </summary>
    ''' <param name=""loggerAction"">An optional action to log exceptions that occur while raising events.</param>
    ''' <remarks>
    ''' <para>
    ''' This method is thread-safe and should be called during a phase where event handling is safe,
    ''' such as during the 'Draw' phase in game frameworks.
    ''' </para>
    ''' <para>
    ''' Events are raised in the following order:
    ''' <list type=""number"">
    ''' <item><description>Events with higher priority values are raised first</description></item>
    ''' <item><description>Events within the same priority level are raised in FIFO order</description></item>
    ''' </list>
    ''' </para>
    ''' <para>
    ''' After raising all events, the pending events queue is cleared. This method can be called
    ''' multiple times; each call will raise all events that were scheduled since the last call.
    ''' </para>
    ''' </remarks>
    Public Sub RaiseScheduledEvents(Optional loggerAction As Action(Of Exception) = Nothing)
        Dim actionsToRaise As Action() = Array.Empty(Of Action)()
        SyncLock _lock
            If _pendingEvents.Count = 0 Then Exit Sub
            actionsToRaise = Aggregate evt As EventItem In _pendingEvents
                             Order By evt.Priority Descending, evt.Order Ascending
                             Select evt.Event Into ToArray()
            _pendingEvents.Clear()
        End SyncLock

        ' Raise all events outside the lock with exception handling/logging
        For Each atn As Action In actionsToRaise
            Try
                atn.Invoke()
            Catch ex As Exception
                loggerAction?.Invoke(ex)
            End Try
        Next atn
    End Sub

    ''' <summary>
    ''' Gets the number of events that are currently pending execution.
    ''' </summary>
    ''' <value>The number of pending events.</value>
    ''' <remarks>
    ''' This property is thread-safe and may be called from any thread. It can be useful for debugging
    ''' or for implementing logic that depends on the current number of pending events.
    ''' </remarks>
    Public ReadOnly Property PendingEventCount As Integer
        Get
            SyncLock _lock
                Return _pendingEvents.Count
            End SyncLock
        End Get
    End Property

    ''' <summary>
    ''' Clears all scheduled events without raising them.
    ''' </summary>
    ''' <remarks>
    ''' This method is thread-safe and may be called from any thread. Use it when you need to cancel
    ''' all pending events, such as during scene transitions or when resetting game state. After calling
    ''' this method, <see cref=""PendingEventCount""/> will be zero.
    ''' </remarks>
    Public Sub ClearScheduledEvents()
        SyncLock _lock
            _pendingEvents.Clear()
        End SyncLock
    End Sub
End Class"

    Public Const WEAK_EVENT_CLASSDEF As String = "' <auto-generated>
'     This code was generated by `ModuleEventRaiser.Generator`.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Option Explicit On
Option Strict On
Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Linq.Expressions

''' <summary>
''' Provides a thread-safe collection of weakly referenced event handlers that can be invoked
''' without preventing their targets from being garbage collected.
''' </summary>
''' <typeparam name=""TDelegate""><![CDATA[The type of delegate to manage. It must be a delegate type.]]></typeparam>
''' <remarks>
''' <para>
''' This class is designed to help prevent memory leaks in event-driven architectures where long-lived
''' objects subscribe to events raised by shorter-lived objects. By using weak references, the subscriber
''' can still be garbage collected even if the publisher remains alive.
''' </para>
''' <para>
''' <b>Thread Safety:</b> All methods in this class are thread-safe and can be called from any thread.
''' </para>
''' <para>
''' <b>Performance:</b> Uses strongly-typed invocation (via compiled expression trees) instead of
''' <see cref=""[Delegate].DynamicInvoke""/> for improved performance when raising events.
''' </para>
''' <para>
''' <b>Usage Example:</b>
''' <code lang=""vb"">
''' ' Declare a weak multicast event field in a module
''' Private _myEvent As New WeakMulticastEvent(Of Action(Of Integer))
'''
''' ' Expose as standard VB.NET event in the module using `Custom Event` syntax
''' Public Custom Event MyEvent As Action(Of Integer)
'''     AddHandler(value As Action(Of Integer))
'''         _myEvent.AddHandler(value)
'''     End AddHandler
'''     RemoveHandler(value As Action(Of Integer))
'''         _myEvent.RemoveHandler(value)
'''     End RemoveHandler
'''     RaiseEvent(obj As Integer)
'''         _myEvent.RaiseEvent(obj)
'''     End RaiseEvent
''' End Event
''' </code>
''' </para>
''' </remarks>
Public NotInheritable Class WeakMulticastEvent(Of TDelegate As Class)
    Private Structure HandlerEntry
        Public ReadOnly WeakRef As WeakReference(Of TDelegate)
        Public ReadOnly Method As System.Reflection.MethodInfo
        Public ReadOnly Target As WeakReference

        Public Sub New(handler As TDelegate)
            Dim d As [Delegate] = CType(CObj(handler), [Delegate])
            Me.WeakRef = New WeakReference(Of TDelegate)(handler)
            Me.Method = d.Method
            Me.Target = If(d.Target IsNot Nothing, New WeakReference(d.Target), Nothing)
        End Sub

        Public Function TryGetHandler(ByRef handler As TDelegate) As Boolean
            Return WeakRef.TryGetTarget(handler)
        End Function

        Public Function Matches(handler As TDelegate) As Boolean
            Dim d As [Delegate] = CType(CObj(handler), [Delegate])
            If Not Me.Method.Equals(d.Method) Then Return False

            ' 1. both have no target = match
            ' 2. one has target, other doesn't = no match
            If Me.Target Is Nothing AndAlso d.Target Is Nothing Then Return True
            If Me.Target Is Nothing OrElse d.Target Is Nothing Then Return False

            ' Compare targets - but our target reference may have been collected
            Dim ourTarget As Object = Nothing
            If Me.Target.IsAlive Then ourTarget = Me.Target.Target
            If ourTarget Is Nothing Then Return False
            Return ourTarget.Equals(d.Target)
        End Function
    End Structure

    Private ReadOnly _handlers As New List(Of HandlerEntry)
    Private ReadOnly _lock As New Object
    Private Shared ReadOnly _invoker As Action(Of TDelegate, Object()) = CreateInvokeAction()

    ''' <summary>
    ''' Adds a weakly referenced event handler.
    ''' </summary>
    ''' <param name=""handler""><![CDATA[The event handler to add. It must be a delegate type.]]></param>
    ''' <exception cref=""ArgumentNullException""><![CDATA[Thrown when <paramref name=""handler""/> is Nothing.]]></exception>
    ''' <exception cref=""ArgumentException""><![CDATA[Thrown when <paramref name=""handler""/> is not a delegate type.]]></exception>
    ''' <remarks>
    ''' Dead handlers are removed from the collection before the new handler is added, helping to keep
    ''' the collection clean and efficient.
    ''' </remarks>
    Public Sub [AddHandler](handler As TDelegate)
        ArgumentNullException.ThrowIfNull(handler)
        If TypeOf handler IsNot [Delegate] Then
            Throw New ArgumentException(""Event handler must be a delegate type."", NameOf(handler))
        End If
        SyncLock _lock
            RemoveDeadHandlersUnlocked()
            _handlers.Add(New HandlerEntry(handler))
        End SyncLock
    End Sub

    ''' <summary>
    ''' Removes an event handler from the collection.
    ''' </summary>
    ''' <param name=""handler"">The event handler to remove.</param>
    ''' <remarks>
    ''' This removes the specified handler when present and also removes any dead handlers from the
    ''' collection. If the handler is not found, no action is taken.
    ''' </remarks>
    Public Sub [RemoveHandler](handler As TDelegate)
        If handler Is Nothing Then Exit Sub
        SyncLock _lock
            _handlers.RemoveAll(
                Function(entry)
                    Dim target As TDelegate = Nothing
                    
                    ' Remove if collected OR if it matches the handler being removed
                    Return Not entry.TryGetHandler(target) OrElse entry.Matches(handler)
                End Function)
        End SyncLock
    End Sub

    ''' <summary>
    ''' Raises the event by invoking all live handlers with the specified arguments.
    ''' </summary>
    ''' <param name=""args""><![CDATA[The arguments to pass to the event handlers.]]></param>
    ''' <remarks>
    ''' <para>
    ''' Dead handlers are removed from the collection before the live handlers are invoked, ensuring that
    ''' only active handlers are called and keeping the collection efficient.
    ''' </para>
    ''' <para>
    ''' The implementation uses compiled expression trees for strongly typed invocation, which is significantly
    ''' faster than <see cref=""[Delegate].DynamicInvoke""/>.
    ''' </para>
    ''' </remarks>
    Public Sub [RaiseEvent](ParamArray args As Object())
        Dim liveHandlers As New List(Of TDelegate)
        SyncLock _lock
            ' Iterate backward to safely remove dead handlers without skipping elements
            For i As Integer = _handlers.Count - 1 To 0 Step -1
                Dim target As TDelegate = Nothing
                If _handlers(i).TryGetHandler(target) Then
                    liveHandlers.Add(target)
                Else
                    _handlers.RemoveAt(i)
                End If
            Next i
        End SyncLock
        ' Invoke all handlers outside the lock to avoid deadlocks
        For Each hdlr In liveHandlers
            _invoker(hdlr, args)
        Next hdlr
    End Sub

    ''' <summary>
    ''' Gets the number of active event handlers in the collection.
    ''' </summary>
    ''' <value>The number of active event handlers.</value>
    ''' <remarks>
    ''' This property is thread-safe and may be called from any thread. It counts only handlers whose
    ''' targets are still reachable by the garbage collector.
    ''' </remarks>
    Public ReadOnly Property ActiveHandlerCount As Integer
        Get
            SyncLock _lock
                Dim count As Integer = 0
                For Each he In _handlers
                    Dim target As TDelegate = Nothing
                    If he.TryGetHandler(target) Then count += 1
                Next he
                Return count
            End SyncLock
        End Get
    End Property

    ''' <summary>
    ''' Removes all event handlers from the collection, whether they are alive or dead.
    ''' </summary>
    ''' <remarks>
    ''' This method is thread-safe and may be called from any thread. After calling it,
    ''' <see cref=""ActiveHandlerCount""/> will return zero.
    ''' </remarks>
    Public Sub Clear()
        SyncLock _lock
            _handlers.Clear()
        End SyncLock
    End Sub

    ''' <summary>
    ''' Removes handlers whose targets have already been garbage collected.
    ''' </summary>
    ''' <remarks>
    ''' This method is thread-safe and may be called from any thread. It is useful for keeping the
    ''' internal collection clean when handlers are not being added or removed actively.
    ''' </remarks>
    Public Sub RemoveDeadHandlers()
        SyncLock _lock
            RemoveDeadHandlersUnlocked()
        End SyncLock
    End Sub

    ''' <summary>
    ''' Removes dead handlers. Caller must hold <see cref=""_lock""/>.
    ''' </summary>
    Private Sub RemoveDeadHandlersUnlocked()
        For i As Integer = _handlers.Count - 1 To 0 Step -1
            Dim target As TDelegate = Nothing
            If Not _handlers(i).TryGetHandler(target) Then
                _handlers.RemoveAt(i)
            End If
        Next i
    End Sub

    ''' <summary>
    ''' Creates a strongly typed invocation delegate for the specified delegate type.
    ''' </summary>
    ''' <returns>An action that invokes the delegate with the specified arguments.</returns>
    ''' <exception cref=""InvalidOperationException""><![CDATA[Thrown when the delegate type does not expose an Invoke method.]]></exception>
    Private Shared Function CreateInvokeAction() As Action(Of TDelegate, Object())
        Dim delegateType = GetType(TDelegate)
        Dim invokeMethod = delegateType.GetMethod(""Invoke"")
        If invokeMethod Is Nothing Then Throw New InvalidOperationException(
            $""Delegate type '{delegateType.Name}' does not have an Invoke method."")

        ' Create expression tree for strongly-typed invocation
        Dim delegateParam = Expression.Parameter(delegateType, ""handler"")
        Dim argsParam = Expression.Parameter(GetType(Object()), ""args"")

        ' Convert arguments to match the delegate's parameter types
        Dim parameters = invokeMethod.GetParameters()
        Dim argExpressions = parameters.Select(
            Function(p, i)
                Return Expression.Convert(
                    Expression.ArrayIndex(argsParam, Expression.Constant(i)),
                    p.ParameterType
                )
            End Function).ToArray()

        ' Create invocation expression
        Dim invokeExpression = Expression.Call(delegateParam, invokeMethod, argExpressions)

        ' Compile and return the strongly-typed action
        Return Expression.Lambda(Of Action(Of TDelegate, Object()))(
            invokeExpression, delegateParam, argsParam
        ).Compile()
    End Function
End Class"
End Module